version: '3.3'
services:
  post_db:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - front_net
      - back_net

  ui:
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/ui
    ports:
      - ${HOST_PORT}:${DOCKER_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/post:latest
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/comment
    networks:
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--storage.tsdb.retension=1d'
    networks:
      - back_net
      - front_net

  node-export:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesysten.ignored-mount-points="^(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
